resolver: lts-8.3
packages:
- dbrecord
- dbrecord-postgres-simple
- dbrecord-mysql-haskell
- dbrecord-mongo
- dbrecord-mssql-odbc
- dbrecord-sqlite-simple
- dbrecord-test-common

extra-deps:
- mysql-haskell-0.8.0.0
- binary-ieee754-0.1.0.0
- binary-parsers-0.2.3.0
- wire-streams-0.1.1.0
- word24-2.0.1
- tcp-streams-0.6.0.0
- mongoDB-2.2.0
- mysql-haskell-nem-0.1.0.0
- git: https://github.com/byteally/mssql-odbc.git
  commit: 0cf8cb5dfb13343b64839ca0cc4cd979234411d9
