resolver: ghc-8.0.0 
packages:
- '.'
extra-deps:
- text-1.2.2.1
- aeson-0.11.1.4
- uuid-types-1.0.3
- vector-0.11.0.0
- attoparsec-0.13.0.2
- dlist-0.7.1.2
- fail-4.9.0.0
- hashable-1.2.4.0
- mtl-2.2.1
- primitive-0.6.1.0
- random-1.1
- scientific-0.3.4.6
- syb-0.6
- tagged-0.8.4
- unordered-containers-0.2.7.0
- resource-pool-0.2.3.2
- monad-control-1.0.1.0
- stm-2.4.4.1
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- postgresql-simple-0.5.1.2
- bytestring-builder-0.10.6.0.0
- case-insensitive-1.2.0.6
- postgresql-libpq-0.9.1.1
flags: {}
extra-package-dbs: []